"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

import Card from "../ui/Card";
import Input from "../ui/Input";
import Button from "../ui/Button";
import SettingsFeedback, { type SettingsMessage } from "./SettingsFeedback";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import type { AIProviderStatus } from "@/lib/ai/aiProviderStatus";
import {
  assignWhatsAppChannel,
  saveWhatsAppChannel,
  type WhatsAppChannel,
} from "@/lib/whatsappChannels";

interface WhatsAppSetupProps {
  employeeId: string;
  assignmentEnabled: boolean;
  webhookConfigured: boolean;
  inboundReady: boolean;
  aiProviderStatus: AIProviderStatus;
  channels: WhatsAppChannel[];
}

function StatusRow({
  ok,
  label,
  detail,
}: {
  ok: boolean | null;
  label: string;
  detail: string;
}) {
  const color =
    ok === null
      ? "bg-amber-400"
      : ok
        ? "bg-emerald-400"
        : "bg-red-400";

  return (
    <div className="flex items-start gap-3">
      <span className={`mt-1.5 h-2.5 w-2.5 rounded-full ${color}`} aria-hidden />
      <div>
        <p className="text-sm font-medium text-white">{label}</p>
        <p className="text-sm text-zinc-400">{detail}</p>
      </div>
    </div>
  );
}

function aiProviderStatusRow(status: AIProviderStatus): {
  ok: boolean | null;
  label: string;
  detail: string;
} {
  if (status.kind === "openai" && status.ready) {
    return {
      ok: true,
      label: "AI provider: OpenAI active",
      detail:
        "Drafts are generated by the configured OpenAI model when inbound processing is ready.",
    };
  }

  if (status.kind === "openai") {
    return {
      ok: false,
      label: "AI provider: OpenAI incomplete",
      detail:
        "AI_PROVIDER=openai is set, but OPENAI_API_KEY and OPENAI_MODEL are not both configured. Drafts fall back to the safe mock provider.",
    };
  }

  if (status.kind === "unsupported") {
    return {
      ok: false,
      label: `AI provider: unsupported "${status.value}"`,
      detail:
        "The configured AI_PROVIDER value is not recognised. Drafts fall back to the safe mock provider.",
    };
  }

  return {
    ok: null,
    label: "AI provider: safe mock (default)",
    detail:
      "Drafts are generated by the built-in safe mock provider until a production provider is configured.",
  };
}

export default function WhatsAppSetup({
  employeeId,
  assignmentEnabled,
  webhookConfigured,
  inboundReady,
  aiProviderStatus,
  channels,
}: WhatsAppSetupProps) {
  const router = useRouter();

  const [phoneNumberId, setPhoneNumberId] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [saving, setSaving] = useState(false);
  const [assigningChannelId, setAssigningChannelId] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<SettingsMessage | null>(null);

  async function handleSave(e: React.FormEvent) {
    e.preventDefault();

    const supabase = createSupabaseBrowserClient();

    if (!supabase) {
      setFeedback({
        type: "error",
        text: "WhatsApp channel settings are temporarily unavailable. Please try again later.",
      });
      return;
    }

    setSaving(true);
    setFeedback(null);

    const result = await saveWhatsAppChannel(supabase, {
      phoneNumberId,
      displayName,
      ...(assignmentEnabled ? { employeeId } : {}),
    });

    setSaving(false);

    if (result.error) {
      setFeedback({ type: "error", text: result.error });
      return;
    }

    setFeedback({
      type: "success",
      text: assignmentEnabled
        ? "WhatsApp channel linked and assigned to this AI Employee."
        : "WhatsApp channel linked. AI assignment remains safely disabled.",
    });
    setPhoneNumberId("");
    setDisplayName("");
    router.refresh();
  }

  async function handleAssign(channelId: string) {
    const supabase = createSupabaseBrowserClient();
    if (!supabase) {
      setFeedback({
        type: "error",
        text: "WhatsApp channel settings are temporarily unavailable. Please try again later.",
      });
      return;
    }

    setAssigningChannelId(channelId);
    setFeedback(null);
    const result = await assignWhatsAppChannel(supabase, channelId, employeeId);
    setAssigningChannelId(null);

    if (result.error) {
      setFeedback({ type: "error", text: result.error });
      return;
    }

    setFeedback({ type: "success", text: "WhatsApp channel assigned to this AI Employee." });
    router.refresh();
  }

  return (
    <Card className="space-y-6">

      <div>
        <h2 className="text-2xl font-bold">
          WhatsApp Setup
        </h2>

        <p className="text-zinc-400 mt-1">
          Connect your WhatsApp Business number and check pipeline status.
        </p>
        <p className="mt-3 rounded-lg border border-amber-700/50 bg-amber-950/30 p-3 text-sm text-amber-300">
          Meta phone-number registration is pending. Inbound events are processed
          using the configured AI provider; production outbound sending stays disabled.
        </p>
      </div>

      <div className="space-y-4 rounded-xl border border-zinc-800 bg-zinc-900/60 p-4">
        <StatusRow
          ok={webhookConfigured}
          label={webhookConfigured ? "Webhook configured" : "Webhook not configured"}
          detail={
            webhookConfigured
              ? "Signed webhook endpoint and verification token are set on the server."
              : "Set WHATSAPP_VERIFY_TOKEN and WHATSAPP_APP_SECRET on the server to accept Meta webhooks."
          }
        />

        <StatusRow
          ok={inboundReady}
          label={inboundReady ? "Inbound processing ready" : "Inbound processing not ready"}
          detail={
            inboundReady
              ? "Events are deduplicated, stored as conversations, and answered by the AI provider below."
              : "Set SUPABASE_SERVICE_ROLE_KEY (server only) so the processor can store conversations."
          }
        />

        <StatusRow
          ok={aiProviderStatusRow(aiProviderStatus).ok}
          label={aiProviderStatusRow(aiProviderStatus).label}
          detail={aiProviderStatusRow(aiProviderStatus).detail}
        />

        <StatusRow
          ok={
            assignmentEnabled
              ? channels.some((channel) => channel.ai_employee_id === employeeId)
              : null
          }
          label={
            !assignmentEnabled
              ? "AI assignment rollout disabled"
              : channels.some((channel) => channel.ai_employee_id === employeeId)
                ? "Channel assigned to this AI Employee"
                : "No channel assigned to this AI Employee"
          }
          detail={
            !assignmentEnabled
              ? "Inbound messages can be stored, but no AI draft is generated until the reviewed migration and live safety tests pass."
              : channels.some((channel) => channel.ai_employee_id === employeeId)
                ? "Only this employee's verified context can be used for drafts from the assigned channel."
                : "Assign a linked channel below. Unassigned channels store inbound messages without generating an AI draft."
          }
        />

        <StatusRow
          ok={false}
          label="Outbound sending blocked by Meta"
          detail="Replies are stored as drafts until the phone number passes Meta registration and WHATSAPP_OUTBOUND_ENABLED is turned on."
        />
      </div>

      {channels.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-zinc-300">Linked channels</h3>
          <ul className="space-y-2">
            {channels.map((channel) => (
              <li
                key={channel.id}
                className="rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-2 text-sm"
              >
                <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <span className="text-white">{channel.display_name || "WhatsApp channel"}</span>
                    <span className="ml-2 font-mono text-xs text-zinc-400">
                      ID {channel.phone_number_id}
                    </span>
                    {assignmentEnabled ? (
                      <p className="mt-1 text-xs text-zinc-400">
                        {channel.ai_employee_id === employeeId
                          ? "Assigned to this AI Employee"
                          : channel.ai_employee_id
                            ? "Assigned to another AI Employee"
                            : "Unassigned — inbound storage only; no AI draft"}
                      </p>
                    ) : null}
                  </div>
                  {assignmentEnabled && channel.ai_employee_id !== employeeId ? (
                    <Button
                      type="button"
                      disabled={assigningChannelId !== null}
                      aria-busy={assigningChannelId === channel.id}
                      onClick={() => handleAssign(channel.id)}
                    >
                      {assigningChannelId === channel.id ? "Assigning…" : "Assign here"}
                    </Button>
                  ) : null}
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}

      {feedback ? (
        <SettingsFeedback id="whatsapp-settings-feedback" message={feedback} />
      ) : null}

      <form onSubmit={handleSave} className="space-y-6" aria-busy={saving}>
        <div>
          <label htmlFor="whatsapp-phone-number-id" className="mb-1.5 block text-sm font-medium text-zinc-200">
            Meta Phone Number ID
          </label>
          <Input
            id="whatsapp-phone-number-id"
            name="whatsapp-phone-number-id"
            placeholder="From your WhatsApp Business account"
            maxLength={200}
            value={phoneNumberId}
            onChange={(e) => setPhoneNumberId(e.target.value)}
            required
          />
        </div>

        <div>
          <label htmlFor="whatsapp-display-name" className="mb-1.5 block text-sm font-medium text-zinc-200">
            Display Name <span className="text-zinc-400">(optional)</span>
          </label>
          <Input
            id="whatsapp-display-name"
            name="whatsapp-display-name"
            placeholder="WhatsApp channel name"
            maxLength={200}
            value={displayName}
            onChange={(e) => setDisplayName(e.target.value)}
          />
        </div>

        <div className="pt-2">
          <Button type="submit" disabled={saving} aria-busy={saving}>
            {saving
              ? "Linking…"
              : assignmentEnabled
                ? "Link and assign to this employee"
                : "Link WhatsApp Number"}
          </Button>
        </div>

      </form>

    </Card>
  );
}
